spring:
  application:
    name: ics-generator

del:
  clubs:
    - city: Mannheim
      club: Adler Mannheim
      address: SAP Arena Mannheim
      contraction: MAN
    - city: Augsburg
      club: Augsburger Panther
      address: Curt-Frenzel-Stadion Augsburg
      contraction: AEV
    - city: Düsseldorf
      club: Düsseldorfer EG
      address: ISS Dome Düsseldorf
      contraction: DEG
    - city: Köln
      club: Kölner Haie
      address: Lanxess Arena Köln
      contraction: KEC
    - city: München
      club: EHC Red Bull München
      address: Olympia-Eisstadion München
      contraction: RBM
    - city: Straubing
      club: Straubing Tigers
      address: Eisstadion am Pulverturm Straubing
      contraction: STR
    - city: Berlin
      club: Eisbären Berlin
      address: Mercedes-Benz Arena Berlin
      contraction: EBB
    - city: Ingolstadt
      club: ERC Ingolstadt
      address: Saturn Arena Ingolstadt
      contraction: ING
    - city: Krefeld
      club: Krefeld Pinguine
      address: Yayla Arena Krefeld
      contraction: KEV
    - city: Nürnberg
      club: Thomas Sabo Ice Tigers
      address: Arena Nürnberger Versicherung Nürnberg
      contraction: NIT
    - city: Wolfsburg
      club: Grizzlys Wolfsburg
      address: Eis Arena Wolfsburg
      contraction: WOB
    - city: Bremerhaven
      club: Fischtown Pinguins
      address: Eisarena am Wilhelm-Kaisen-Platz Bremerhaven
      contraction: BHV
    - city: Iserlohn
      club: Iserlohn Roosters
      address: Eissporthalle am Seilersee Iserlohn
      contraction: IEC
    - city: Schwenningen
      club: Schwenninger Wild Wings
      address: Helios-Arena Schwenningen
      contraction: SWW

chl:
  clubs:
      # 2019
    - city: Wien
      club: Vienna Capitals
      address: Erste Bank Arena
      contraction:
    - city: Tychy
      club: GKS Tychy
      address: Stadion Zimowy w Tychach
      contraction:
    - city: Stockholm
      club: Djurgårdens IF
      address: Hovet Stockholm
      contraction:

test:
  clubs:
      # 2019
    - city: Biel
      club: EHC Biel
      # address: Tissot Arena Biel
      address: Eishalle Bergholz Wil
      contraction:
    - city: Zürich
      club: ZSC Lions
      # address: Hallenstadion Zürich
      address: Eishalle Bergholz Wil
      contraction:
    - city: Jönköping
      club: HV71 Jönköping
      address: Kinnarps Arena Jönköping
      contraction:
    - city: Genf
      club: Genève-Servette HC
      address: Les Vernets Genf
      contraction:
    - city: Genf
      club: HC Servette Genève
      address: Les Vernets Genf
      contraction:
    - city: Prag
      club: HC Sparta Prag
      address: O2 Arena Prag
      contraction: